-- Generated by scripts/generate-supabase-seed.mjs from data/launch-courts.json.
-- Re-running is safe: slug is the stable import key.
insert into public.courts (
  slug, name, short_name, address, city, state, postal_code, market, location,
  latitude, longitude, sport_type, access_type, setting, court_count,
  launch_reason, launch_priority, verification_status, source_url, source_tier,
  geocode_source, geocode_query, detection_source_id, detection_distance_m,
  satellite_match_status, indoor
)
values
  (
    'new-york-city-basketball-rucker-park', 'Holcombe Rucker Park', 'Rucker Park', '280 W 155th St',
    'New York', 'NY', '10039', 'New York City', 'New York',
    40.8288869, -73.9368503, 'basketball', 'public_free', 'outdoor',
    null, 'iconic', 100, 'source_verified',
    'https://www.nycgovparks.org/parks/holcombe-rucker-park', 'official', 'OpenStreetMap Nominatim', '280 W 155th St, New York, NY 10039',
    '1074962572', 84.6, 'strong',
    false
  ),
  (
    'new-york-city-basketball-the-cage', 'West 4th Street Courts', 'The Cage', '6th Avenue & West 3rd Street',
    'New York', 'NY', '10014', 'New York City', 'New York',
    40.7308271, -74.0013897, 'basketball', 'public_free', 'outdoor',
    1, 'iconic', 100, 'source_verified',
    'https://www.nycgovparks.org/parks/west-4th-street-courts/', 'official', 'OpenStreetMap Nominatim', '6th Avenue & West 3rd Street, Manhattan, New York, NY 10014',
    '440055116', 38.9, 'strong',
    false
  ),
  (
    'new-york-city-basketball-dyckman', 'Dyckman Park Courts', 'Dyckman', '4768 Nagle Ave',
    'New York', 'NY', '10034', 'New York City', 'New York',
    40.860319, -73.9282121, 'basketball', 'public_free', 'outdoor',
    null, 'iconic', 100, 'source_verified',
    'https://www.redbull.com/us-en/famous-streetball-courts-usa', 'editorial', 'OpenStreetMap Nominatim', '4768 Nagle Ave, New York, NY 10034',
    '766058280', 399.5, 'review',
    false
  ),
  (
    'new-york-city-basketball-kingdome', 'Kingdome', 'Kingdome', '62 Malcolm X Blvd',
    'New York', 'NY', '10026', 'New York City', 'New York',
    40.8003258, -73.9503163, 'basketball', 'public_free', 'outdoor',
    null, 'iconic', 100, 'source_verified',
    'https://www.redbull.com/us-en/famous-streetball-courts-usa', 'editorial', 'OpenStreetMap Nominatim', '62 Malcolm X Blvd, New York, NY 10026',
    '225143099', 26.1, 'strong',
    false
  ),
  (
    'new-york-city-pickleball-marine-park', 'Marine Park Pickleball Courts', 'Marine Park', 'Fillmore Ave & Stuart St',
    'Brooklyn', 'NY', '11234', 'New York City', 'Brooklyn',
    40.6072902, -73.9393511, 'pickleball', 'public_free', 'outdoor',
    8, 'open_play_anchor', 92, 'source_verified',
    'https://www.nycpickleball.com/the-guide', 'community', 'OpenStreetMap Nominatim', 'Fillmore Ave & Stuart St, Brooklyn, NY 11234',
    null, null, 'not_applicable',
    false
  ),
  (
    'new-york-city-pickleball-pier-2', 'Pier 2 Pickleball Courts', 'Pier 2', '150 Furman St',
    'Brooklyn', 'NY', '11201', 'New York City', 'Brooklyn',
    40.70189, -73.995468, 'pickleball', 'public_free', 'outdoor_covered',
    4, 'open_play_anchor', 92, 'source_verified',
    'https://www.nycpickleball.com/blog/pier-2-pickleball-courts-brooklyn-heights', 'community', 'OpenStreetMap Nominatim', '150 Furman St, Brooklyn, NY 11201',
    null, null, 'not_applicable',
    false
  ),
  (
    'new-york-city-pickleball-john-j-carty', 'John J. Carty Park', 'John J. Carty', '9902 Fort Hamilton Pkwy',
    'Brooklyn', 'NY', '11209', 'New York City', 'Brooklyn',
    40.6125402, -74.0316587, 'pickleball', 'public_free', 'outdoor',
    4, 'open_play_anchor', 92, 'source_verified',
    'https://www.nycgovparks.org/parks/john-j-carty-park/facilities/pickleball', 'official', 'OpenStreetMap Nominatim', '9902 Fort Hamilton Pkwy, Brooklyn, NY 11209',
    null, null, 'not_applicable',
    false
  ),
  (
    'new-york-city-pickleball-james-j-walker', 'James J. Walker Park', 'James J. Walker', '100 Clarkson St',
    'New York', 'NY', '10014', 'New York City', 'New York',
    40.7295766, -74.0076736, 'pickleball', 'public_free', 'outdoor',
    2, 'neighborhood_hub', 78, 'source_verified',
    'https://www.nycgovparks.org/facilities/pickleball', 'official', 'OpenStreetMap Nominatim', '100 Clarkson St, New York, NY 10014',
    null, null, 'not_applicable',
    false
  ),
  (
    'washington-dc-basketball-banneker', 'Banneker Recreation Center', 'Banneker', '2500 Georgia Ave NW',
    'Washington', 'DC', '20001', 'Washington DC', 'Washington',
    38.922453, -77.022378, 'basketball', 'public_free', 'outdoor',
    null, 'pickup_anchor', 90, 'source_verified',
    'https://dpr.dc.gov/page/athletic-fields-courts', 'official', 'OpenStreetMap Nominatim', '2500 Georgia Ave NW, Washington, DC 20001',
    '87483737', 99, 'nearby',
    false
  ),
  (
    'washington-dc-basketball-turkey-thicket', 'Turkey Thicket Recreation Center', 'Turkey Thicket', '1100 Michigan Ave NE',
    'Washington', 'DC', '20017', 'Washington DC', 'Washington',
    38.9380885, -76.9928164, 'basketball', 'public_free', 'mixed',
    null, 'community_hub', 82, 'source_verified',
    'https://dpr.dc.gov/page/athletic-fields-courts', 'official', 'OpenStreetMap Nominatim', '1100 Michigan Ave NE, Washington, DC 20017',
    '982098880', 82.8, 'strong',
    null
  ),
  (
    'washington-dc-basketball-kennedy-rec', 'Kennedy Recreation Center', 'Kennedy Rec', '1401 7th St NW',
    'Washington', 'DC', '20001', 'Washington DC', 'Washington',
    38.909034, -77.0215468, 'basketball', 'public_free', 'mixed',
    null, 'pickup_anchor', 90, 'source_verified',
    'https://dpr.dc.gov/page/athletic-fields-courts', 'official', 'OpenStreetMap Nominatim', 'Kennedy Recreation Center, 1401 7th St NW, Washington, DC 20001',
    '197099235', 54, 'strong',
    null
  ),
  (
    'washington-dc-basketball-takoma-rec', 'Takoma Recreation Center', 'Takoma Rec', '300 Van Buren St NW',
    'Washington', 'DC', '20012', 'Washington DC', 'Washington',
    38.9689287, -77.0179738, 'basketball', 'public_free', 'mixed',
    null, 'community_hub', 82, 'source_verified',
    'https://dpr.dc.gov/page/athletic-fields-courts', 'official', 'OpenStreetMap Nominatim', '300 Van Buren St NW, Washington, DC 20012',
    '134179172', 182.2, 'nearby',
    null
  ),
  (
    'washington-dc-pickleball-turkey-thicket', 'Turkey Thicket Pickleball Courts', 'Turkey Thicket', '1100 Michigan Ave NE',
    'Washington', 'DC', '20017', 'Washington DC', 'Washington',
    38.9380885, -76.9928164, 'pickleball', 'public_free', 'mixed',
    null, 'open_play_anchor', 92, 'source_verified',
    'https://dpr.dc.gov/release/dpr-announces-arrival-pickleball', 'official', 'OpenStreetMap Nominatim', '1100 Michigan Ave NE, Washington, DC 20017',
    null, null, 'not_applicable',
    null
  ),
  (
    'washington-dc-pickleball-palisades', 'Palisades Recreation Center', 'Palisades', '5200 Sherier Pl NW',
    'Washington', 'DC', '20016', 'Washington DC', 'Washington',
    38.9244362, -77.1045859, 'pickleball', 'public_free', 'mixed',
    null, 'neighborhood_hub', 78, 'source_verified',
    'https://dpr.dc.gov/page/athletic-fields-courts', 'official', 'OpenStreetMap Nominatim', 'Palisades Recreation Center, 5200 Sherier Pl NW, Washington, DC 20016',
    null, null, 'not_applicable',
    null
  ),
  (
    'washington-dc-pickleball-hearst', 'Hearst Recreation Center', 'Hearst', '3950 37th St NW',
    'Washington', 'DC', '20008', 'Washington DC', 'Washington',
    38.9408873, -77.0716987, 'pickleball', 'public_free', 'outdoor',
    null, 'neighborhood_hub', 78, 'source_verified',
    'https://dpr.dc.gov/page/athletic-fields-courts', 'official', 'OpenStreetMap Nominatim', '3950 37th St NW, Washington, DC 20008',
    null, null, 'not_applicable',
    false
  ),
  (
    'washington-dc-pickleball-edgewood', 'Edgewood Recreation Center', 'Edgewood', '301 Franklin St NE',
    'Washington', 'DC', '20002', 'Washington DC', 'Washington',
    38.925512, -77.002286, 'pickleball', 'public_free', 'indoor',
    null, 'open_play_anchor', 92, 'source_verified',
    'https://dpr.dc.gov/page/athletic-fields-courts', 'official', 'OpenStreetMap Nominatim', '301 Franklin St NE, Washington, DC 20002',
    null, null, 'not_applicable',
    true
  ),
  (
    'miami-basketball-lummus-park', 'Lummus Park Courts', 'Lummus Park', '1130 Ocean Dr',
    'Miami Beach', 'FL', '33139', 'Miami', 'Miami Beach',
    25.7823481, -80.1305196, 'basketball', 'public_free', 'outdoor',
    null, 'pickup_anchor', 90, 'source_verified',
    'https://fullcourt.io/miami/courts', 'community', 'OpenStreetMap Nominatim', '1130 Ocean Dr, Miami Beach, FL 33139',
    null, null, 'none',
    false
  ),
  (
    'miami-basketball-flamingo-park', 'Flamingo Park', 'Flamingo Park', '1200 Meridian Ave',
    'Miami Beach', 'FL', '33139', 'Miami', 'Miami Beach',
    25.7851826, -80.1375022, 'basketball', 'public_free', 'outdoor',
    null, 'pickup_anchor', 90, 'source_verified',
    'https://www.miamibeachfl.gov/parks-facilities/flamingo-park/', 'official', 'OpenStreetMap Nominatim', '1200 Meridian Ave, Miami Beach, FL 33139',
    '237435647', 105.9, 'nearby',
    false
  ),
  (
    'miami-basketball-margaret-pace', 'Margaret Pace Park', 'Margaret Pace', '1745 N Bayshore Dr',
    'Miami', 'FL', '33132', 'Miami', 'Miami',
    25.7933775, -80.1861208, 'basketball', 'public_free', 'outdoor',
    null, 'pickup_anchor', 90, 'source_verified',
    'https://www.miami.gov/Parks-Public-Places/Parks-Directory/Margaret-Pace-Park', 'official', 'OpenStreetMap Nominatim', '1745 N Bayshore Dr, Miami, FL 33132',
    '316001421', 232.2, 'review',
    false
  ),
  (
    'miami-basketball-morningside', 'Morningside Park', 'Morningside', '750 NE 55th Ter',
    'Miami', 'FL', '33137', 'Miami', 'Miami',
    25.8270704, -80.1802162, 'basketball', 'public_free', 'outdoor',
    null, 'neighborhood_hub', 78, 'source_verified',
    'https://fullcourt.io/miami/courts', 'community', 'OpenStreetMap Nominatim', '750 NE 55th Ter, Miami, FL 33137',
    '313742328', 127.8, 'nearby',
    false
  ),
  (
    'miami-pickleball-tropical-park', 'Tropical Park Pickleball Courts', 'Tropical Park', '7900 SW 40th St',
    'Miami', 'FL', '33155', 'Miami', 'Miami',
    25.732893, -80.319927, 'pickleball', 'public_free', 'outdoor',
    null, 'open_play_anchor', 92, 'source_verified',
    'https://www.miamidade.gov/parks/tropical.asp', 'official', 'OpenStreetMap Nominatim', '7900 SW 40th St, Miami, FL 33155',
    null, null, 'not_applicable',
    false
  ),
  (
    'miami-pickleball-miami-shores', 'Miami Shores Tennis & Pickleball Club', 'Miami Shores', '825 NE 100th St',
    'Miami Shores', 'FL', '33138', 'Miami', 'Miami Shores',
    25.8674557, -80.1807216, 'pickleball', 'public_paid', 'outdoor',
    6, 'open_play_anchor', 92, 'source_verified',
    'https://www.miamishorestennis.com/', 'venue', 'OpenStreetMap Nominatim', '825 NE 100th St, Miami Shores, FL 33138',
    null, null, 'not_applicable',
    false
  ),
  (
    'miami-pickleball-north-shore', 'North Shore Park Pickleball Courts', 'North Shore', '501 72nd St',
    'Miami Beach', 'FL', '33141', 'Miami', 'Miami Beach',
    25.8573686, -80.1229567, 'pickleball', 'public_paid', 'outdoor',
    null, 'open_play_anchor', 92, 'source_verified',
    'https://www.mbtennisacademy.com/pickleball-openplay', 'venue', 'OpenStreetMap Nominatim', '501 72nd St, Miami Beach, FL 33141',
    null, null, 'not_applicable',
    false
  ),
  (
    'miami-pickleball-palmetto-bay', 'Palmetto Bay Park', 'Palmetto Bay', '17535 SW 95th Ave',
    'Palmetto Bay', 'FL', '33157', 'Miami', 'Palmetto Bay',
    25.6070706, -80.345553, 'pickleball', 'public_free', 'outdoor',
    null, 'community_hub', 82, 'source_verified',
    'https://www.palmettobay-fl.gov/Facilities/Facility/Details/Palmetto-Bay-Park-5', 'official', 'OpenStreetMap Nominatim', '17535 SW 95th Ave, Palmetto Bay, FL 33157',
    null, null, 'not_applicable',
    false
  ),
  (
    'los-angeles-basketball-venice-beach', 'Venice Beach Basketball Courts', 'Venice Beach', '1800 Ocean Front Walk',
    'Venice', 'CA', '90291', 'Los Angeles', 'Venice',
    33.98567, -118.472727, 'basketball', 'public_free', 'outdoor',
    null, 'iconic', 100, 'source_verified',
    'https://www.redbull.com/us-en/famous-streetball-courts-usa', 'editorial', 'OpenStreetMap Nominatim', '1800 Ocean Front Walk, Venice, CA 90291',
    '35565733', 29, 'strong',
    false
  ),
  (
    'los-angeles-basketball-pan-pacific', 'Pan Pacific Park', 'Pan Pacific', '7600 Beverly Blvd',
    'Los Angeles', 'CA', '90036', 'Los Angeles', 'Los Angeles',
    34.076049, -118.355142, 'basketball', 'public_free', 'outdoor',
    2, 'pickup_anchor', 90, 'source_verified',
    'https://www.cbsnews.com/losangeles/news/best-outdoor-basketball-courts-in-los-angeles', 'editorial', 'OpenStreetMap Nominatim', '7600 Beverly Blvd, Los Angeles, CA 90036',
    '202014022', 140.7, 'nearby',
    false
  ),
  (
    'los-angeles-basketball-washington-park', 'Col. Leon H. Washington Park', 'Washington Park', '8908 S Maie Ave',
    'Los Angeles', 'CA', '90002', 'Los Angeles', 'Los Angeles',
    33.9499854, -118.2445129, 'basketball', 'public_free', 'mixed',
    null, 'iconic', 100, 'source_verified',
    'https://locator.lacounty.gov/lac/Location/3179832/col-leon-h-washington-park', 'official', 'OpenStreetMap Nominatim', '8908 S Maie Ave, Los Angeles, CA 90002',
    null, null, 'none',
    null
  ),
  (
    'los-angeles-basketball-rancho-cienega', 'Rancho Cienega Sports Complex', 'Rancho Cienega', '5001 Obama Blvd',
    'Los Angeles', 'CA', '90016', 'Los Angeles', 'Los Angeles',
    34.0229782, -118.3514764, 'basketball', 'public_free', 'mixed',
    null, 'community_hub', 82, 'source_verified',
    'https://www.laparks.org/reccenter/rancho-cienega', 'official', 'OpenStreetMap Nominatim', '5001 Obama Blvd, Los Angeles, CA 90016',
    null, null, 'none',
    null
  ),
  (
    'los-angeles-pickleball-plummer-park', 'Plummer Park Pickleball Courts', 'Plummer Park', '7377 Santa Monica Blvd',
    'West Hollywood', 'CA', '90046', 'Los Angeles', 'West Hollywood',
    34.0906544, -118.3506583, 'pickleball', 'public_free', 'outdoor',
    null, 'open_play_anchor', 92, 'source_verified',
    'https://www.weho.org/community/recreation-services/parks/plummer-park', 'official', 'OpenStreetMap Nominatim', '7377 Santa Monica Blvd, West Hollywood, CA 90046',
    null, null, 'not_applicable',
    false
  ),
  (
    'los-angeles-pickleball-memorial-park', 'Memorial Park Pickleball Courts', 'Memorial Park', '1401 Olympic Blvd',
    'Santa Monica', 'CA', '90404', 'Los Angeles', 'Santa Monica',
    34.019769, -118.480427, 'pickleball', 'public_free', 'outdoor',
    null, 'open_play_anchor', 92, 'source_verified',
    'https://www.santamonica.gov/places/parks/memorial-park', 'official', 'OpenStreetMap Nominatim', '1401 Olympic Blvd, Santa Monica, CA 90404',
    null, null, 'not_applicable',
    false
  ),
  (
    'los-angeles-pickleball-mar-vista', 'Mar Vista Recreation Center', 'Mar Vista', '11430 Woodbine St',
    'Los Angeles', 'CA', '90066', 'Los Angeles', 'Los Angeles',
    34.0178894, -118.4293305, 'pickleball', 'public_free', 'outdoor',
    null, 'community_hub', 82, 'source_verified',
    'https://www.laparks.org/reccenter/mar-vista', 'official', 'OpenStreetMap Nominatim', '11430 Woodbine St, Los Angeles, CA 90066',
    null, null, 'not_applicable',
    false
  ),
  (
    'los-angeles-pickleball-cheviot-hills', 'Cheviot Hills Recreation Center', 'Cheviot Hills', '2551 Motor Ave',
    'Los Angeles', 'CA', '90064', 'Los Angeles', 'Los Angeles',
    34.0468111, -118.4081458, 'pickleball', 'public_free', 'outdoor',
    null, 'neighborhood_hub', 78, 'source_verified',
    'https://www.laparks.org/reccenter/cheviot-hills', 'official', 'OpenStreetMap Nominatim', '2551 Motor Ave, Los Angeles, CA 90064',
    null, null, 'not_applicable',
    false
  ),
  (
    'houston-basketball-fonde-rec', 'Fonde Recreation Center', 'Fonde Rec', '110 Sabine St',
    'Houston', 'TX', '77007', 'Houston', 'Houston',
    29.7629552, -95.3750088, 'basketball', 'public_free', 'indoor',
    null, 'iconic', 100, 'source_verified',
    'https://www.houstontx.gov/parks/communitycenters/fondecc.html', 'official', 'OpenStreetMap Nominatim', '110 Sabine St, Houston, TX 77007',
    '984550959', 421.4, 'review',
    true
  ),
  (
    'houston-basketball-emancipation', 'Emancipation Park', 'Emancipation', '3018 Emancipation Ave',
    'Houston', 'TX', '77004', 'Houston', 'Houston',
    29.7356906, -95.3648855, 'basketball', 'public_free', 'outdoor',
    null, 'community_hub', 82, 'source_verified',
    'https://epconservancy.org/', 'venue', 'OpenStreetMap Nominatim', 'Emancipation Park, 3018 Emancipation Ave, Houston, TX 77004',
    '398628438', 38.8, 'strong',
    false
  ),
  (
    'houston-basketball-macgregor', 'MacGregor Park', 'MacGregor', '5225 Calhoun Rd',
    'Houston', 'TX', '77021', 'Houston', 'Houston',
    29.710711, -95.3415957, 'basketball', 'public_free', 'outdoor',
    null, 'pickup_anchor', 90, 'source_verified',
    'https://www.houstontx.gov/parks/parksites/macgregorpark.html', 'official', 'OpenStreetMap Nominatim', '5225 Calhoun Rd, Houston, TX 77021',
    null, null, 'none',
    false
  ),
  (
    'houston-basketball-root-square', 'Root Memorial Square', 'Root Square', '1400 Clay St',
    'Houston', 'TX', '77002', 'Houston', 'Houston',
    29.751741, -95.363759, 'basketball', 'public_free', 'outdoor',
    1, 'downtown_anchor', 74, 'source_verified',
    'https://www.houstontx.gov/parks/parksites/rootmemorialsquare.html', 'official', 'OpenStreetMap Nominatim', '1400 Clay St, Houston, TX 77002',
    '263245741', 55, 'strong',
    false
  ),
  (
    'houston-pickleball-houston-pickleball', 'Houston Pickleball Center', 'Houston Pickleball', '12233 Robin Blvd',
    'Houston', 'TX', '77045', 'Houston', 'Houston',
    29.6338243, -95.406236, 'pickleball', 'private_paid', 'indoor',
    11, 'open_play_anchor', 92, 'source_verified',
    'https://houstonpickleballcenter.com/', 'venue', 'OpenStreetMap Nominatim', 'Houston Pickleball Center, 12233 Robin Blvd, Houston, TX 77045',
    null, null, 'not_applicable',
    true
  ),
  (
    'houston-pickleball-bumpy-pickle', 'Bumpy Pickle', 'Bumpy Pickle', '554 Lockwood Dr',
    'Houston', 'TX', '77011', 'Houston', 'Houston',
    29.7525981, -95.3226971, 'pickleball', 'private_paid', 'outdoor',
    9, 'open_play_anchor', 92, 'source_verified',
    'https://bumpypickle.com/open-play', 'venue', 'OpenStreetMap Nominatim', '554 Lockwood Dr, Houston, TX 77011',
    null, null, 'not_applicable',
    false
  ),
  (
    'houston-pickleball-east-river-9', 'East River 9', 'East River 9', '65 Hirsch Rd',
    'Houston', 'TX', '77020', 'Houston', 'Houston',
    29.7617406, -95.3317626, 'pickleball', 'private_paid', 'outdoor',
    null, 'social_anchor', 86, 'source_verified',
    'https://eastriver9.com/pickleball/', 'venue', 'OpenStreetMap Nominatim', 'East River 9, 65 Hirsch Rd, Houston, TX 77020',
    null, null, 'not_applicable',
    false
  ),
  (
    'houston-pickleball-jaycee-park', 'Jaycee Park Pickleball Courts', 'Jaycee Park', '1300 Seamist Dr',
    'Houston', 'TX', '77008', 'Houston', 'Houston',
    29.793367, -95.437836, 'pickleball', 'public_free', 'outdoor',
    2, 'community_hub', 82, 'source_verified',
    'https://cp4.harriscountytx.gov/Explore/Parks/Precinct-4-Parks/jaycee', 'official', 'OpenStreetMap Nominatim', '1300 Seamist Dr, Houston, TX 77008',
    null, null, 'not_applicable',
    false
  ),
  (
    'austin-basketball-hancock', 'Hancock Recreation Center', 'Hancock', '811 E 41st St',
    'Austin', 'TX', '78751', 'Austin', 'Austin',
    30.2990529, -97.7245946, 'basketball', 'public_free', 'outdoor',
    2, 'pickup_anchor', 90, 'source_verified',
    'https://austinparks.org/blog/basketball-courts-austin-texas/', 'community', 'OpenStreetMap Nominatim', 'Hancock Recreation Center, 811 E 41st St, Austin, TX 78751',
    '900177898', 33.6, 'strong',
    false
  ),
  (
    'austin-basketball-givens', 'Givens Recreation Center', 'Givens', '3811 E 12th St',
    'Austin', 'TX', '78721', 'Austin', 'Austin',
    30.2768, -97.6902958, 'basketball', 'public_free', 'mixed',
    null, 'community_hub', 82, 'source_verified',
    'https://austinparks.org/blog/basketball-courts-austin-texas/', 'community', 'OpenStreetMap Nominatim', 'Givens Recreation Center, 3811 E 12th St, Austin, TX 78721',
    '583734035', 233.5, 'review',
    null
  ),
  (
    'austin-basketball-pan-am', 'Pan American Recreation Center', 'Pan Am', '2100 E 3rd St',
    'Austin', 'TX', '78702', 'Austin', 'Austin',
    30.2581662, -97.7207643, 'basketball', 'public_free', 'mixed',
    null, 'community_hub', 82, 'source_verified',
    'https://austinparks.org/blog/basketball-courts-austin-texas/', 'community', 'OpenStreetMap Nominatim', '2100 E 3rd St, Austin, TX 78702',
    '1259442487', 315, 'review',
    null
  ),
  (
    'austin-basketball-garrison', 'Garrison District Park', 'Garrison', '6001 Manchaca Rd',
    'Austin', 'TX', '78745', 'Austin', 'Austin',
    30.1685841, -97.8306185, 'basketball', 'public_free', 'outdoor',
    null, 'neighborhood_hub', 78, 'source_verified',
    'https://austinparks.org/blog/basketball-courts-austin-texas/', 'community', 'OpenStreetMap Nominatim', '6001 Manchaca Rd, Austin, TX 78745',
    null, null, 'none',
    false
  ),
  (
    'austin-pickleball-pan-am', 'Pan American Pickleball Courts', 'Pan Am', '2100 E 3rd St',
    'Austin', 'TX', '78702', 'Austin', 'Austin',
    30.2581662, -97.7207643, 'pickleball', 'public_free', 'outdoor',
    6, 'open_play_anchor', 92, 'source_verified',
    'https://www.austintexas.gov/parks/programs/pickleball', 'official', 'OpenStreetMap Nominatim', '2100 E 3rd St, Austin, TX 78702',
    null, null, 'not_applicable',
    false
  ),
  (
    'austin-pickleball-atpc', 'Austin Tennis & Pickleball Center', 'ATPC', '7800 Johnny Morris Rd',
    'Austin', 'TX', '78724', 'Austin', 'Austin',
    30.312221, -97.638456, 'pickleball', 'public_paid', 'outdoor',
    8, 'open_play_anchor', 92, 'source_verified',
    'https://www.austintexas.gov/department/austin-tennis-center', 'official', 'OpenStreetMap Nominatim', '7800 Johnny Morris Rd, Austin, TX 78724',
    null, null, 'not_applicable',
    false
  ),
  (
    'austin-pickleball-patterson-park', 'Patterson Neighborhood Park', 'Patterson Park', '4200 Brookview Rd',
    'Austin', 'TX', '78722', 'Austin', 'Austin',
    30.2966713, -97.7102822, 'pickleball', 'public_free', 'outdoor',
    2, 'neighborhood_hub', 78, 'source_verified',
    'https://www.austintexas.gov/parks/programs/pickleball', 'official', 'OpenStreetMap Nominatim', '4200 Brookview Rd, Austin, TX 78722',
    null, null, 'not_applicable',
    false
  ),
  (
    'austin-pickleball-dittmar', 'Dittmar Recreation Center', 'Dittmar', '1009 W Dittmar Rd',
    'Austin', 'TX', '78745', 'Austin', 'Austin',
    30.1858789, -97.8007033, 'pickleball', 'public_free', 'indoor',
    4, 'open_play_anchor', 92, 'source_verified',
    'https://www.austintexas.gov/parks/programs/pickleball', 'official', 'OpenStreetMap Nominatim', '1009 W Dittmar Rd, Austin, TX 78745',
    null, null, 'not_applicable',
    true
  ),
  (
    'denver-basketball-mestizo-curtis', 'Mestizo-Curtis Park', 'Mestizo-Curtis', '3100 Champa St',
    'Denver', 'CO', '80205', 'Denver', 'Denver',
    39.760575, -104.975633, 'basketball', 'public_free', 'outdoor',
    null, 'community_hub', 82, 'source_verified',
    'https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Parks-Recreation/Parks/Urban-Parks/Mestizo-Curtis-Park', 'official', 'OpenStreetMap Nominatim', '3100 Champa St, Denver, CO 80205',
    '25680128', 210.8, 'nearby',
    false
  ),
  (
    'denver-basketball-la-alma-lincoln', 'La Alma-Lincoln Park', 'La Alma-Lincoln', '1325 W 11th Ave',
    'Denver', 'CO', '80204', 'Denver', 'Denver',
    39.734759, -105.0044547, 'basketball', 'public_free', 'outdoor',
    null, 'community_hub', 82, 'source_verified',
    'https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Parks-Recreation/Parks/Urban-Parks/La-Alma-Lincoln-Park', 'official', 'OpenStreetMap Nominatim', '1325 W 11th Ave, Denver, CO 80204',
    '114290702', 26.8, 'strong',
    false
  ),
  (
    'denver-basketball-city-park', 'City Park Basketball Courts', 'City Park', '1700 N York St',
    'Denver', 'CO', '80206', 'Denver', 'Denver',
    39.743383, -104.959677, 'basketball', 'public_free', 'outdoor',
    null, 'city_anchor', 76, 'source_verified',
    'https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Parks-Recreation/Parks/Urban-Parks/City-Park', 'official', 'OpenStreetMap Nominatim', '1700 N York St, Denver, CO 80206',
    '323175182', 499.1, 'review',
    false
  ),
  (
    'denver-basketball-washington-park', 'Washington Park Basketball Courts', 'Washington Park', '701 S Franklin St',
    'Denver', 'CO', '80209', 'Denver', 'Denver',
    39.7026223, -104.9705739, 'basketball', 'public_free', 'mixed',
    null, 'city_anchor', 76, 'source_verified',
    'https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Parks-Recreation/Parks/Urban-Parks/Washington-Park', 'official', 'OpenStreetMap Nominatim', '701 S Franklin St, Denver, CO 80209',
    '1137052158', 221.6, 'review',
    null
  ),
  (
    'denver-pickleball-gates', 'Gates Tennis Center', 'Gates', '3300 E Bayaud Ave',
    'Denver', 'CO', '80209', 'Denver', 'Denver',
    39.7139193, -104.9483282, 'pickleball', 'public_paid', 'outdoor',
    14, 'open_play_anchor', 92, 'source_verified',
    'https://www.gatestenniscenter.info/', 'venue', 'OpenStreetMap Nominatim', 'Gates Tennis Center, 3300 E Bayaud Ave, Denver, CO 80209',
    null, null, 'not_applicable',
    false
  ),
  (
    'denver-pickleball-mlk-park', 'Martin Luther King Jr. Park Courts', 'MLK Park', '3880 Newport St',
    'Denver', 'CO', '80207', 'Denver', 'Denver',
    39.7707141, -104.9092894, 'pickleball', 'public_free', 'outdoor',
    10, 'open_play_anchor', 92, 'source_verified',
    'https://dnvrpickleball.com/denver/courts', 'community', 'OpenStreetMap Nominatim', '3880 Newport St, Denver, CO 80207',
    null, null, 'not_applicable',
    false
  ),
  (
    'denver-pickleball-eisenhower-park', 'Mamie D. Eisenhower Park Courts', 'Eisenhower Park', '4300 E Dartmouth Ave',
    'Denver', 'CO', '80222', 'Denver', 'Denver',
    39.6596571, -104.937437, 'pickleball', 'public_free', 'mixed',
    7, 'community_hub', 82, 'source_verified',
    'https://dnvrpickleball.com/denver/courts', 'community', 'OpenStreetMap Nominatim', '4300 E Dartmouth Ave, Denver, CO 80222',
    null, null, 'not_applicable',
    null
  ),
  (
    'denver-pickleball-huston-lake', 'Huston Lake Park Courts', 'Huston Lake', '910 S Bryant St',
    'Denver', 'CO', '80219', 'Denver', 'Denver',
    39.700157, -105.0179623, 'pickleball', 'public_free', 'outdoor',
    4, 'open_play_anchor', 92, 'source_verified',
    'https://dnvrpickleball.com/denver/courts', 'community', 'OpenStreetMap Nominatim', '910 S Bryant St, Denver, CO 80219',
    null, null, 'not_applicable',
    false
  )
on conflict (slug) do update set
  name = excluded.name,
  short_name = excluded.short_name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  postal_code = excluded.postal_code,
  market = excluded.market,
  location = excluded.location,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  sport_type = excluded.sport_type,
  access_type = excluded.access_type,
  setting = excluded.setting,
  court_count = excluded.court_count,
  launch_reason = excluded.launch_reason,
  launch_priority = excluded.launch_priority,
  verification_status = excluded.verification_status,
  source_url = excluded.source_url,
  source_tier = excluded.source_tier,
  geocode_source = excluded.geocode_source,
  geocode_query = excluded.geocode_query,
  detection_source_id = excluded.detection_source_id,
  detection_distance_m = excluded.detection_distance_m,
  satellite_match_status = excluded.satellite_match_status,
  indoor = excluded.indoor,
  is_archived = false;
