import { ArrowLeft, Check, CornersOut } from "@phosphor-icons/react/dist/ssr";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — LocalCheck",
  description: "How LocalCheck collects, uses, shares, and protects information.",
};

const sections = [
  ["scope", "Scope"],
  ["information", "Information we collect"],
  ["use", "How we use information"],
  ["sharing", "How we share information"],
  ["retention", "Retention and deletion"],
  ["choices", "Your choices and rights"],
  ["security", "Security"],
  ["children", "Children's privacy"],
  ["changes", "Changes to this policy"],
  ["contact", "Contact us"],
] as const;

function PrivacyBrand() {
  return (
    <Link className="brand brand--compact" href="/" aria-label="LocalCheck home">
      <span className="brand__mark" aria-hidden="true">
        <CornersOut size={27} weight="regular" />
        <Check className="brand__check" size={14} weight="bold" />
      </span>
      <span className="brand__word">LOCALCHECK</span>
    </Link>
  );
}

export default function PrivacyPolicy() {
  return (
    <main className="legal-page" id="top">
      <header className="legal-header">
        <PrivacyBrand />
        <Link className="legal-back" href="/" aria-label="Back to LocalCheck">
          <ArrowLeft size={16} weight="bold" /> <span className="legal-back__label">Back to LocalCheck</span>
        </Link>
      </header>

      <section className="legal-hero" aria-labelledby="privacy-title">
        <div>
          <span className="eyebrow eyebrow--orange">LocalCheck legal</span>
          <h1 id="privacy-title">Privacy<br />Policy<span>.</span></h1>
        </div>
        <div className="legal-meta" aria-label="Policy publication details">
          <p><span>Effective date</span><strong>August 13, 2026</strong></p>
          <p><span>Operator</span><strong>Jesse Herrig</strong></p>
        </div>
      </section>

      <div className="legal-layout">
        <aside className="legal-index" aria-label="Privacy policy sections">
          <span>On this page</span>
          <nav>
            {sections.map(([id, label], index) => (
              <a href={`#${id}`} key={id}><small>{String(index + 1).padStart(2, "0")}</small>{label}</a>
            ))}
          </nav>
        </aside>

        <article className="legal-copy">
          <p className="legal-intro">
            LocalCheck is operated by Jesse Herrig. This Privacy Policy explains how LocalCheck
            (&ldquo;LocalCheck,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) collects, uses, shares, and protects information
            when you use the LocalCheck mobile application, website, and related services.
          </p>

          <section id="scope">
            <span className="legal-section-number">01</span>
            <h2>Scope</h2>
            <p>
              This policy applies to the LocalCheck mobile app, website, and services that link to
              this policy. It does not apply to third-party websites, apps, or services that have
              their own privacy policies.
            </p>
          </section>

          <section id="information">
            <span className="legal-section-number">02</span>
            <h2>Information we collect</h2>
            <h3>Information you provide</h3>
            <ul>
              <li><strong>Account and profile information.</strong> Your name, email address, user identifier, sign-in provider, and profile details.</li>
              <li><strong>Court and activity information.</strong> Court submissions, check-ins, local-court selections, planned visits, verification results, and other activity you choose to share through LocalCheck.</li>
              <li><strong>Photos.</strong> Photos you take or select when submitting a court for verification. The submitted image is sent through our backend to Google Gemini for analysis. The current verification flow does not retain the image after that analysis.</li>
              <li><strong>Communications.</strong> Information you include when you contact us for support or privacy questions.</li>
            </ul>
            <h3>Information collected when you use LocalCheck</h3>
            <ul>
              <li><strong>Location.</strong> With your permission, LocalCheck uses precise location to show courts near you and support location-based app features. You can deny or withdraw this permission in your device settings.</li>
              <li><strong>Notification information.</strong> A device push token and notification preferences when you enable notifications.</li>
              <li><strong>Technical and usage information.</strong> Device, browser, IP address, diagnostic, security, and service-usage information generated by LocalCheck and its service providers.</li>
            </ul>
            <p>
              Some profile and court-activity information is designed to be visible to other
              LocalCheck users. The app identifies public information at the point where you share it.
            </p>
          </section>

          <section id="use">
            <span className="legal-section-number">03</span>
            <h2>How we use information</h2>
            <p>We use information to:</p>
            <ul>
              <li>create and secure accounts and provide LocalCheck features;</li>
              <li>show nearby courts, maps, check-ins, planned visits, and local activity;</li>
              <li>process and verify court submissions;</li>
              <li>send notifications you choose to receive;</li>
              <li>respond to support and privacy requests;</li>
              <li>detect abuse, protect users, troubleshoot problems, and improve reliability; and</li>
              <li>comply with law and enforce our agreements.</li>
            </ul>
            <p>LocalCheck does not use personal information for third-party advertising or cross-app tracking.</p>
          </section>

          <section id="sharing">
            <span className="legal-section-number">04</span>
            <h2>How we share information</h2>
            <p>We share information only as needed to operate LocalCheck, including with:</p>
            <ul>
              <li><strong>Supabase</strong> for authentication, databases, backend functions, and service infrastructure;</li>
              <li><strong>Mapbox</strong> for maps and location-based court discovery;</li>
              <li><strong>Google Gemini</strong> to analyze submitted court-verification photos;</li>
              <li><strong>Apple and Expo</strong> for sign-in, app services, distribution, and notifications; and</li>
              <li>professional advisers, authorities, or other parties when required by law, needed to protect rights and safety, or involved in a business transfer.</li>
            </ul>
            <p>
              Information you make public through LocalCheck may be seen by other users. We do not
              sell personal information and do not share personal information for cross-context
              behavioral advertising.
            </p>
          </section>

          <section id="retention">
            <span className="legal-section-number">05</span>
            <h2>Retention and deletion</h2>
            <p>
              We keep personal information only for as long as reasonably necessary to provide
              LocalCheck, meet legal and safety obligations, resolve disputes, and enforce our
              agreements. Retention can vary by data type and purpose.
            </p>
            <p>
              You can initiate permanent account deletion inside the LocalCheck app. Account
              deletion removes or de-identifies associated personal information unless we must keep
              limited information for legal, security, fraud-prevention, or backup purposes. When
              deletion involves Sign in with Apple, LocalCheck also initiates revocation of the
              associated Apple authorization. Court-verification photos are analyzed for the
              submission and are not retained by the current verification flow afterward.
            </p>
          </section>

          <section id="choices">
            <span className="legal-section-number">06</span>
            <h2>Your choices and rights</h2>
            <ul>
              <li><strong>Account information.</strong> You can update available profile details in the app.</li>
              <li><strong>Location, camera, photos, and notifications.</strong> You can manage these permissions in your device settings.</li>
              <li><strong>Account deletion.</strong> Use the Delete Account option inside LocalCheck to start permanent deletion.</li>
              <li><strong>Privacy requests.</strong> Depending on where you live, you may have rights to access, correct, delete, or receive a copy of your personal information, or to object to or restrict certain processing.</li>
            </ul>
            <p>
              To make a privacy request, email <a href="mailto:localchecksports@gmail.com">localchecksports@gmail.com</a>.
              We may need to verify your identity before completing a request.
            </p>
          </section>

          <section id="security">
            <span className="legal-section-number">07</span>
            <h2>Security</h2>
            <p>
              We use reasonable administrative, technical, and organizational measures designed to
              protect personal information. No system or transmission method is completely secure,
              so we cannot guarantee absolute security.
            </p>
          </section>

          <section id="children">
            <span className="legal-section-number">08</span>
            <h2>Children&apos;s privacy</h2>
            <p>
              LocalCheck is not directed to children under 13, and we do not knowingly collect
              personal information from children under 13. If you believe a child has provided
              personal information, contact us so we can investigate and take appropriate action.
            </p>
          </section>

          <section id="changes">
            <span className="legal-section-number">09</span>
            <h2>Changes to this policy</h2>
            <p>
              We may update this policy as LocalCheck changes. We will post the revised policy here
              and update the effective date. If a change is material, we will provide additional
              notice when required.
            </p>
          </section>

          <section id="contact">
            <span className="legal-section-number">10</span>
            <h2>Contact us</h2>
            <p>
              For questions or requests about this policy or LocalCheck&apos;s privacy practices, contact:
            </p>
            <address>
              <strong>Jesse Herrig</strong>
              <span>LocalCheck</span>
              <a href="mailto:localchecksports@gmail.com">localchecksports@gmail.com</a>
            </address>
          </section>
        </article>
      </div>

      <footer className="legal-footer">
        <PrivacyBrand />
        <Link href="#top">Back to top</Link>
        <span>© 2026 LocalCheck</span>
      </footer>
    </main>
  );
}
