import Link from "next/link";
import type { Metadata } from "next";
export const metadata: Metadata = { title: "Terms of Use — LocalCheck", description: "Terms for using LocalCheck courts, community features, and LocalPlus." };
export default function Terms() {
  return <main className="legal-page">
    <header className="legal-header"><Link className="brand" href="/">LOCALCHECK</Link><Link href="/">← Back to LocalCheck</Link></header>
    <section className="legal-hero"><div><span className="eyebrow eyebrow--orange">LocalCheck legal</span><h1>Terms of Use<span>.</span></h1></div><div className="legal-meta"><p><span>Effective date</span><strong>September 6, 2026</strong></p><p><span>Contact</span><strong>LocalCheck Support</strong></p></div></section>
    <article className="legal-copy section">
      <p>LocalCheck is operated by Jesse Harrick. These terms govern your use of the LocalCheck website, app, and community services. By using LocalCheck, you agree to these terms and our <Link href="/privacy">Privacy Policy</Link>.</p>
      <section><h2>Using LocalCheck</h2><p>Provide accurate account information and keep your account secure. Do not impersonate others, manipulate scores or rankings, submit false court information, abuse the service, or attempt unauthorized access. LocalCheck is not directed to children under 13.</p></section>
      <section><h2>Courts and in-person play</h2><p>Listings, check-ins, and planned games help players coordinate. They do not guarantee venue access, court availability, player attendance, safety, or accurate current conditions. Follow venue rules, check local conditions, and use your judgment when meeting others. LocalCheck does not operate the listed courts or reserve them on your behalf.</p></section>
      <section><h2>Your contributions and community conduct</h2><p>Submit only content you have the right to share. Do not post abusive, threatening, discriminatory, sexual, illegal, or misleading content, or expose another person’s private information. You retain your rights in your content and allow LocalCheck to store, process, and display it as needed to provide the service and respect your settings.</p><p>Use the app’s report and block controls or contact support about harmful conduct. We may review reports, remove content, and restrict accounts that violate these terms. Game results may be reviewed, disputed, corrected, or invalidated through the app’s available review process.</p></section>
      <section><h2>LocalPlus</h2><p>LocalPlus is an optional membership. The purchase screen describes the available monthly or yearly plan, its price, duration, and included features before you confirm. Apple processes App Store purchases. Auto-renewing subscriptions renew unless canceled through your Apple account settings. Cancellation normally stops the next renewal while access continues through the paid period, subject to Apple’s handling of refunds and billing issues.</p><p>Manage or cancel subscriptions through Apple. Deleting the app or your LocalCheck account does not cancel a subscription. Refund requests for App Store purchases are handled by Apple. Use the app’s restore option when available to recover eligible purchases.</p><p>A promotional access grant is separate from a paid subscription. Any eligibility, duration, and expiry are communicated when the grant is offered. Starter status alone does not promise permanent access to every LocalPlus feature.</p><p>The iOS app license is also subject to <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/">Apple’s Standard Licensed Application End User License Agreement</a>.</p></section>
      <section><h2>Service changes and account closure</h2><p>Features may change as LocalCheck develops. We may interrupt service for maintenance or security and restrict use for violations of these terms. You can stop using LocalCheck and initiate account deletion in the app. Nothing in these terms removes rights you have under applicable consumer law.</p></section>
      <section><h2>Contact and updates</h2><p>Questions, reports, or account requests: <a href="mailto:localchecksports@gmail.com">localchecksports@gmail.com</a>. We will post updated terms here and provide additional notice of material changes where required.</p></section>
    </article><footer className="legal-footer"><Link href="/support">LocalCheck Support</Link><Link href="/privacy">Privacy Policy</Link><Link href="/">Home</Link></footer>
  </main>;
}
